### PR TITLE
feat: implement a better way to resolve remote and upstream branch

### PR DESCRIPTION
**Pull request by guoyiteng**
### Problem
From #110 
> When multiple remotes are returned from git remote, this extension defaults to using the first returned remote name. This can be frustrating when the first remote name is not the desired remote to use.

And 
when the local branch name doesn't exist in the remote, the link generated by the current implementation leads to a 404 Not Found (See https://github.com/sourcegraph/sourcegraph-vscode/pull/24#issuecomment-634181548). 

### Changes
Use `git rev-parse --abbrev-ref HEAD@{upstream}` to resolve the remote name and upstream branch. Use the remote if it exists instead of the first remote in the list. It could potentially solve the issue mentioned in #110. This command could also resolve the upstream branch if it exists. If not, it will use `HEAD` instead. This should solve the second problem mentioned above.

### Tests
Mannually run `open file in sourcegraph` in the following scenarios:
local branch -> upstream branch -> sourcegraph
1. local: master -> upstream: origin/master -> sourcegraph: master
2. local: test ->  upstream: origin/test -> sourcegraph: test
3. local: test2 -> upstream: test1 (local branch) -> sourcegraph: master
4. local: test2 -> no upstream -> sourcegraph: master
5. local: detached HEAD -> N/A -> sourcegraph: master

### CODE REVIEW

**Comment by nicksnyder** [comment]
@guoyiteng Can you fix the merge conflict?

@sourcegraph/web can anyone review this?

**Review by tjkandala — APPROVED** [review]
Looks good, thanks for the fixes!

**Comment by nicksnyder** [comment]
@tjkandala can you figure out how to actually do a release (is it automatic?)

**Comment by tjkandala** [comment]
@nicksnyder It's supposed to release automatically, but it looks like I need to create a new personal access token (our current token has expired)

**Comment by felixfbecker** [comment]
@tjkandala did you resolve this (create a new token) or is there still action needed?

**Comment by felixfbecker** [comment]
I noticed that the latest release in Git tags (1.2.0) was ahead of the latest release  in the marketplace (1.1.0) therefor I deleted the 1.2.0 tag and updated the token (also migrated to GitHub actions #137).

**Pull request merged**
